"""initial tables

Revision ID: 871ccf101389
Revises: 
Create Date: 2026-03-26 22:44:59.863598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '871ccf101389'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrape_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('query', sa.String(length=500), nullable=False),
    sa.Column('location', sa.String(length=500), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('total_scraped', sa.Integer(), nullable=False),
    sa.Column('total_cleaned', sa.Integer(), nullable=False),
    sa.Column('total_deduped', sa.Integer(), nullable=False),
    sa.Column('total_exported', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('companies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('company_name', sa.String(length=500), nullable=False),
    sa.Column('company_name_normalized', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('phone_normalized', sa.String(length=20), nullable=True),
    sa.Column('phone_display', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=200), nullable=True),
    sa.Column('email_validated', sa.Boolean(), nullable=False),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('website_alive', sa.Boolean(), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('address_normalized', sa.String(length=500), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=10), nullable=True),
    sa.Column('zip', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('scraped_at', sa.DateTime(), nullable=True),
    sa.Column('enriched_at', sa.DateTime(), nullable=True),
    sa.Column('social_links', sa.JSON(), nullable=True),
    sa.Column('is_duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('pipeline_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['is_duplicate_of'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['scrape_tasks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_id')
    )
    op.create_index('ix_companies_category', 'companies', ['category'], unique=False)
    op.create_index('ix_companies_city', 'companies', ['city'], unique=False)
    op.create_index('ix_companies_needs_review', 'companies', ['needs_review'], unique=False)
    op.create_index('ix_companies_source', 'companies', ['source'], unique=False)
    op.create_index('ix_companies_state', 'companies', ['state'], unique=False)
    op.create_index('ix_companies_task_id', 'companies', ['task_id'], unique=False)
    op.create_table('export_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('format', sa.String(length=20), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=True),
    sa.Column('rows_exported', sa.Integer(), nullable=False),
    sa.Column('exported_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['scrape_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pipeline_stats',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=50), nullable=False),
    sa.Column('count_in', sa.Integer(), nullable=False),
    sa.Column('count_out', sa.Integer(), nullable=False),
    sa.Column('count_removed', sa.Integer(), nullable=False),
    sa.Column('count_modified', sa.Integer(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['scrape_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pipeline_stats')
    op.drop_table('export_log')
    op.drop_index('ix_companies_task_id', table_name='companies')
    op.drop_index('ix_companies_state', table_name='companies')
    op.drop_index('ix_companies_source', table_name='companies')
    op.drop_index('ix_companies_needs_review', table_name='companies')
    op.drop_index('ix_companies_city', table_name='companies')
    op.drop_index('ix_companies_category', table_name='companies')
    op.drop_table('companies')
    op.drop_table('scrape_tasks')
    # ### end Alembic commands ###
